#!/bin/sh

export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
#unset DBUS_SESSION_BUS_ADDRESS
#export DBUS_SESSION_BUS_ADDRESS="$HOME/.DBUS"

export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"
export XMODIFIERS="@im=ibus"
DISPLAY=:1 gsettings set org.gnome.settings-daemon.plugins.keyboard active false
DISPLAY=:1 gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule':<'ibus'>}"
im-config -n fcitx
ibus-daemon -drx &

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources


xsetroot -solid grey
#vncconfig -iconic &
exec gnome-session &
service dbus start &
gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
gnome-shell &
#gnome-terminal &
