name: Docker

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag gaainf/ubuntu-chrome:3.4.0-einsteinium --build-arg VERSION=3.4.0-einsteinium
